"""add status column

Revision ID: 815117190b75
Revises: bcbcea3a19ed
Create Date: 2025-05-26 16:21:11.364224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '815117190b75'
down_revision: Union[str, None] = 'bcbcea3a19ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pdf_manager', sa.Column('status', sa.String(), nullable=True))
    op.add_column('pdf_manager', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pdf_manager', 'created_at')
    op.drop_column('pdf_manager', 'status')
    # ### end Alembic commands ###
