"""create pdf_manager table

Revision ID: bcbcea3a19ed
Revises: 
Create Date: 2025-05-26 16:17:02.242346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcbcea3a19ed'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pdf_manager',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('original_image_link', sa.String(), nullable=False),
    sa.Column('redacted_image_link', sa.String(), nullable=True),
    sa.Column('llm_response', sa.Text(), nullable=True),
    sa.Column('input_token_count', sa.Integer(), nullable=True),
    sa.Column('output_token_count', sa.Integer(), nullable=True),
    sa.Column('latency', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pdf_manager_id'), 'pdf_manager', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pdf_manager_id'), table_name='pdf_manager')
    op.drop_table('pdf_manager')
    # ### end Alembic commands ###
